/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;

/**
 *
 * @author nidaf
 */
public class hitungGaji extends javax.swing.JFrame {

    /**
     * Creates new form hitungGaji
     */
    public hitungGaji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulTxt = new javax.swing.JLabel();
        nikLbl = new javax.swing.JLabel();
        namaLbl = new javax.swing.JLabel();
        jkLbl = new javax.swing.JLabel();
        golLbl = new javax.swing.JLabel();
        gapokLbl = new javax.swing.JLabel();
        potongLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        nikTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        priaBtn = new javax.swing.JRadioButton();
        wanitaBtn = new javax.swing.JRadioButton();
        golBox = new javax.swing.JComboBox<>();
        gapokTxt = new javax.swing.JTextField();
        potongTxt = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        judulTxt.setText("HITUNG GAJI KARYAWAN");

        nikLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nikLbl.setText("NIK");

        namaLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        namaLbl.setText("Nama");

        jkLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jkLbl.setText("Jenis Kelamin");

        golLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        golLbl.setText("Golongan");

        gapokLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gapokLbl.setText("Gaji Pokok");

        potongLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        potongLbl.setText("Potongan");

        totalLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        totalLbl.setText("Total");

        namaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTxtActionPerformed(evt);
            }
        });

        priaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priaBtn.setText("Pria");

        wanitaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wanitaBtn.setText("Wanita");

        golBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        golBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Golongan ---", "Golongan 1", "Golongan 2", "Golongan 3", "Golongan 4" }));
        golBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golBoxActionPerformed(evt);
            }
        });

        gapokTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gapokTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Rp.");

        jLabel2.setText("Rp.");

        jLabel3.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulTxt)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nikLbl)
                    .addComponent(namaLbl)
                    .addComponent(jkLbl)
                    .addComponent(golLbl)
                    .addComponent(gapokLbl)
                    .addComponent(potongLbl)
                    .addComponent(totalLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(wanitaBtn)
                        .addGap(252, 252, 252))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priaBtn)
                                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(golBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gapokTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(potongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(judulTxt)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nikLbl)
                    .addComponent(nikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLbl)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLbl)
                    .addComponent(priaBtn)
                    .addComponent(wanitaBtn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(golLbl)
                    .addComponent(golBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gapokLbl)
                    .addComponent(gapokTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potongLbl)
                    .addComponent(potongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLbl)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTxtActionPerformed

    private void golBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golBoxActionPerformed
        switch(golBox.getSelectedIndex()){
        case 0:
            gapokTxt.setText("Rp.");
            break;
        case 1:
            gapokTxt.setText("3500000");
            break;
        case 2:
            gapokTxt.setText("4500000");
            break;
        case 3:
            gapokTxt.setText("5500000");
            break;
        default:
            gapokTxt.setText("6500000");
            break;
        }
    }//GEN-LAST:event_golBoxActionPerformed

    private void gapokTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gapokTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gapokTxtActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new hitungGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gapokLbl;
    private javax.swing.JTextField gapokTxt;
    private javax.swing.JComboBox<String> golBox;
    private javax.swing.JLabel golLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jkLbl;
    private javax.swing.JLabel judulTxt;
    private javax.swing.JLabel namaLbl;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JLabel nikLbl;
    private javax.swing.JTextField nikTxt;
    private javax.swing.JLabel potongLbl;
    private javax.swing.JTextField potongTxt;
    private javax.swing.JRadioButton priaBtn;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JRadioButton wanitaBtn;
    // End of variables declaration//GEN-END:variables
}
